definitions:
  request.CreatePayoutRequest:
    properties:
      currency:
        example: USD
        type: string
      items:
        example:
        - itemId1
        - itemid2
        items:
          type: string
        type: array
    type: object
  response.BatchPayout:
    properties:
      id:
        type: string
      payouts:
        items:
          $ref: '#/definitions/response.Payout'
        type: array
      sales:
        items:
          $ref: '#/definitions/response.Sale'
        type: array
      sellerReference:
        type: string
    type: object
  response.CreatePayoutResponse:
    properties:
      batchPayouts:
        items:
          $ref: '#/definitions/response.BatchPayout'
        type: array
      currency:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  response.Payout:
    properties:
      amount:
        type: number
      id:
        type: string
    type: object
  response.Sale:
    properties:
      id:
        type: string
      itemId:
        type: string
      originalCurrency:
        type: string
      price:
        type: number
    type: object
info:
  contact: {}
paths:
  /payout:
    post:
      consumes:
      - application/json
      description: Takes desired currency and multiple item ids, generates payouts
        respecting the transaction limit, if limit is exceed generates multiple payouts
      parameters:
      - description: Payout Details
        in: body
        name: payout
        required: true
        schema:
          $ref: '#/definitions/request.CreatePayoutRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success Response
          schema:
            $ref: '#/definitions/response.CreatePayoutResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Creates Payouts for Sellers
      tags:
      - Payouts
swagger: "2.0"
